### ISSUE TITLE
Problem Snap Token 

### ISSUE THREAD

**Issue by heydaristo** [heydaristo/SAAS-Project-Management#41]
SQLSTATE[HY000]: General error: 1364 Field 'snap_token' doesn't have a default value
![image](https://github.com/heydaristo/SAAS-Project-Management/assets/94813844/f97a93ba-c565-47e7-9a41-587cfbe5029b)
In register-proses

**Comment by attaf-riski** [comment]
ini karena saat pendaftaran ada pemberian subscripton gratis ke freelance, tapi ngga butuh snap karena ngga perlu ada transaksi, I will fix it
